config/routes.rb
unless Kms.skip_ui
  Kms::Engine.routes.draw do
    devise_for :kms_users,
      class_name: "Kms::User",
      failure_app:  'Kms::Devise::FailureApp',
      module: :devise,
      controllers: { registrations: "users/registrations" }

    constraints(format: "json") do
      resources :templates, except: [:new, :edit], format: true
      resources :snippets, except: [:new, :edit], format: true
      resources :pages, except: [:new, :edit], format: true do
        collection do
          post 'sorting'
        end
      end
      resources :assets, except: [:new, :edit], format: true, as: :kms_assets
      resources :users, only: [:index, :destroy, :update, :show], format: true do
        post :from_kms, on: :collection, action: :create
        get :kms_user, on: :collection
      end
      resources :resources, only: :index, format: true
      resource :settings, only: [:show, :update], format: true

      resources :models, format: true do
        resources :entries, format: true do
          member do
            post '' => 'entries#update'
          end
        end
        resources :fields, only: :update, format: true
      end
    end

    post "/assets/ckeditor" => "assets#ckeditor"

    constraints(format: "html") do
      get "/(*path)" => "kms#index"
    end
  end

  Rails.application.routes.draw do
   root 'kms/public/pages#show'
   get "*path" => "kms/public/pages#show"
   post '/entries/:collection_name' => 'kms/public/entries#create'
  end
end

app/models/concerns/kms/compile_templates.rb
module Kms
  module CompileTemplates
    extend ActiveSupport::Concern

    included do
      validate :compiled_templates
      # on validation step object has no id,
      # that's why we need additional compile if validation pass
      after_commit :compile_templates, on: [:create, :update]
    end

    def register_id
      [self.class.name.parameterize(separator: "_"), id.to_s].join('_')
    end

    protected

    def compiled_templates
      Kms.template_manager.diagnostics.clear
      register_liquor_template
      return if Kms.template_manager.compile
      Kms.template_manager.errors.each do |error|
        splitted_error = error.message.split(':')
        errors.add(:content, [Kms.template_manager.decorate(error), splitted_error].flatten.join('<br>').gsub(/\s/, '&nbsp;'))
      end
    end

    def register_liquor_template
      if is_a?(Kms::Template)
        Kms.template_manager.register_layout(register_id, content, Kms::ExternalsRegistry.externals.keys)
      elsif is_a?(Kms::Page)
        Kms.template_manager.register_template(register_id, content, Kms::ExternalsRegistry.externals.keys)
      elsif is_a?(Kms::Snippet)
        Kms.template_manager.register_partial(register_id, content)
      end
    end

    def compile_templates
      register_liquor_template
      Kms.template_manager.compile
      Settings.set(:dirty, true)
    end
  end
end

app/models/concerns/kms/permalinkable.rb
module Kms
  module Permalinkable
    extend ActiveSupport::Concern

    # Entity should respond to "slug"
    def permalink
      templatable_page = Kms::Page.where(templatable_type: self.class.name).first
      if templatable_page
        Pathname.new(templatable_page.parent.fullpath).join(slug.to_s).to_s
      end
    end
  end
end

app/models/concerns/kms/positioned.rb
module Kms
  module Positioned
    extend ActiveSupport::Concern

    included do
      before_create :set_position
    end

    def set_position
      if parent.present?
        max = parent.children.maximum(:position)
      else
        max = self.class.where('ancestry IS ?', nil).maximum(:position)
      end
      self.position = max ? max + 1 : 0
    end
  end
end

app/models/concerns/kms/update_stylesheets_text.rb
module Kms
  module UpdateStylesheetsText
    extend ActiveSupport::Concern

    included do
      after_commit :restore_text, on: :create
    end

    protected

    def restore_text
      unless stylesheet_or_javascript?
        Asset.where("content_type like '%css%'").each do |asset|
          asset.store_text
          asset.save
        end
      end
    end
  end
end

app/models/kms/asset.rb
module Kms
  class Asset < ActiveRecord::Base
    include UpdateStylesheetsText
    include CompileTemplates

    mount_uploader :file, AssetUploader

    # inspired by Locomotive
    before_validation :store_text

    validate :unique_filename, on: :create

    attr_accessor :text, :performing_plain_text

    def filename
      read_attribute(:file)
    end

    def url
      file.url
    end

    def text
      @text ||= (file.read.force_encoding('UTF-8') rescue nil)
    end

    alias :content :text

    def performing_plain_text?
      performing_plain_text
    end

    def stylesheet_or_javascript?
      stylesheet? || javascript?
    end

    def text_or_javascript?
      text_type? || javascript?
    end

    def stylesheet?
      content_type.include?("css")
    end

    def javascript?
      content_type.include?("javascript")
    end

    def text_type?
      content_type.start_with?("text")
    end

    def store_text
      return if persisted? && !text_or_javascript?

      data = performing_plain_text? ? text : (file.present? ? file.read : nil)

      return if !text_or_javascript? || data.blank?

      cd = CharDet.detect(data)
      encoded_source = data.force_encoding(cd['encoding']).encode('UTF-8') rescue data

      sanitized_source = replace_urls(encoded_source)

      self.file = ::CarrierWave::SanitizedFile.new({
        tempfile: StringIO.new(sanitized_source),
        filename: filename || file.filename
      })

      @text = sanitized_source
    end

    protected

    def unique_filename
      if Asset.where(file: file.filename).exists?
        self.errors.add(:file, I18n.t(:duplicate, scope: [:activerecord, :errors, :messages]))
      end
    end

    # this would replace any url(...) in css files
    # with correct urls to assets that already exist
    def replace_urls(text)
      return if text.blank?

      text.gsub(/url\((\S+)\)/) do |path|
        asset_name = File.basename($1)

        if asset = Asset.where(file: asset_name.gsub(/['"]/, '').gsub(/\?.*/, '')).first
          "url('#{asset.file.url}')"
        else
          path
        end
      end
    end
  end
end

app/models/kms/belongs_to_field.rb
module Kms
  class BelongsToField < Field
    def get_value(entry)
      entry_id = entry.values[liquor_name]
      association_record = Kms::Entry.find_by(id: entry_id)
      Liquor::DropDelegation.wrap_element(association_record)
    end
  end
end

app/models/kms/checkbox_field.rb
module Kms
  class CheckboxField < Field
    def get_value(entry)
      entry.values[liquor_name] == 'true'
    end
  end
end

app/models/kms/date_field.rb
module Kms
  class DateField < Field
  end
end

app/models/kms/entry.rb
module Kms
  class Entry < ActiveRecord::Base
    include Liquor::Dropable
    extend ::FriendlyId
    include CompileTemplates

    friendly_id :slug_candidates, use: :slugged
    belongs_to :model
    after_save :store_files, if: :cache_names_present?

    validates :slug, uniqueness: { scope: :model_id }

    attr_reader :cache_names

    def slug_candidates
      [values[model.label_field]]
    end

    def permalink
      templatable_page = Kms::Page.where(templatable_type: model.name).first
      return nil unless templatable_page
      Pathname.new(templatable_page.parent.fullpath).join(slug.to_s).to_s
    end

    def values
      read_attribute(:values) || {}
    end

    def values=(new_values)
      files_params = new_values.select { |_, v| v.is_a?(ActionDispatch::Http::UploadedFile) || v.is_a?(File) }
      @cache_names ||= {}
      files_params.each do |k, v|
        uploader = EntryFileUploader.new(OpenStruct.new(model: self, field_name: k))
        uploader.cache!(v)
        @cache_names[k] = uploader.cache_name
        files_params[k] = v.original_filename
      end
      super values.merge new_values.merge(files_params)
    end

    def method_missing(name, *args, &block)
      model.fields.where(liquor_name: name.to_s).exists? ? values[name.to_s] : super
    end

    def respond_to_missing?(method_name, include_private = false)
      model.fields.where(liquor_name: method_name.to_s).exists? || super
    end

    protected

    def cache_names_present?
      cache_names.present?
    end

    def store_files
      values.each do |k, v|
        next unless cache_names.keys.include? k
        uploader = EntryFileUploader.new(OpenStruct.new(model: self, field_name: k))
        uploader.retrieve_from_cache!(cache_names[k])
        uploader.store!
      end
    end
  end
end

app/models/kms/field.rb
module Kms
  class Field < ActiveRecord::Base
    belongs_to :model
    scope :file_fields, -> { where(type: Kms::FileField.name) }
    scope :checkbox_fields, -> { where(type: Kms::CheckboxField.name) }
    scope :date_fields, -> { where(type: Kms::DateField.name) }

    def get_value(entry)
      # OVERRIDE in subclasses if needed
      entry.values[liquor_name]
    end
  end
end

app/models/kms/file_field.rb
module Kms
    class FileField < Field
      def get_value(entry)
        value = entry.values[liquor_name]
        uploader = EntryFileUploader.new(OpenStruct.new(model: entry, field_name: liquor_name))
        uploader.retrieve_from_store! value
        uploader.file.exists? ? uploader.url : "not_exists/#{uploader.url}"
      end
    end
end

app/models/kms/has_many_field.rb
module Kms
  class HasManyField < Field
    def get_value(entry)
      entry_ids = entry.values[liquor_name]
      association_records = Kms::Entry.where(id: entry_ids)
      if entry_ids.present?
        # this one allows ORDER BY the IN value list like this example:
        # SELECT * FROM "comments" WHERE ("comments"."id" IN (1,3,2,4))
        # ORDER BY  id=1 DESC, id=3 DESC, id=2 DESC, id=4 DESC
        order_sql = entry_ids.map {|entry_id| "id=#{entry_id} DESC"}
        association_records = association_records.order(order_sql.join(','))
      end
      Liquor::DropDelegation.wrap_scope(association_records)
    end
  end
end

app/models/kms/model.rb
module Kms
  class Model < ActiveRecord::Base
    include CompileTemplates

    has_many :fields, class_name: 'Kms::Field', dependent: :destroy
    has_many :entries, class_name: 'Kms::Entry', dependent: :destroy
    accepts_nested_attributes_for :fields, allow_destroy: true

    validates :kms_model_name, :collection_name, presence: true

    def name
      id.to_s
    end

    # Hacking hack
    def model_name
      value = kms_model_name
      value.instance_eval do
        def human(options={})
          self
        end
      end
      value
    end
  end
end

app/models/kms/models_wrapper.rb
module Kms
  class ModelsWrapper
    include Liquor::Dropable

    def method_missing(name, *args, &block)
      model = Kms::Model.find_by(collection_name: name.to_s)
      model ? model.entries.order('position') : super
    end

    def respond_to_missing?(method_name, include_private = false)
      Kms::Model.where(collection_name: method_name.to_s).exists? || super
    end
  end
end

app/models/kms/page.rb
module Kms
  class Page < ActiveRecord::Base
    include Liquor::Dropable
    include CompileTemplates
    include Positioned

    INDEX_SLUG = 'index'.freeze
    INDEX_FULLPATH = ''
    NOT_FOUND_SLUG = '404'.freeze

    scope :published, lambda { where(published: true) }
    scope :listed, lambda { where(hidden: false) }
    scope :not_templatable, lambda { where(templatable: false) }

    belongs_to :template

    validates :slug, uniqueness: true, presence: true

    before_save :build_fullpath

    has_ancestry

    def self.not_found_page
      where(slug: NOT_FOUND_SLUG).first
    end

    def index?
      slug == INDEX_SLUG
    end

    def not_found?
      slug == NOT_FOUND_SLUG
    end

    def build_fullpath
      if index?
        self.fullpath = INDEX_FULLPATH # self.slug
      else
        slugs = (ancestors + [self]).map(&:slug)
        slugs.shift unless slugs.size == 1
        self.fullpath = File.join slugs.compact
      end
    end

    # fetch item by slug
    def fetch_item(slug)
      return nil unless templatable?
      templatable_type.constantize.find_by_slug!(slug)
    rescue NameError
      model = Kms::Model.find(templatable_type.to_i)
      model.entries.find_by_slug(slug)
      # Kms::Entry.find_by_slug(slug)
    end

    # fetch items for templatable page
    def fetch_items
      templatable_type.constantize.all
    rescue NameError
      # in templatable_type we store id of Kms::Model object in this case
      model = Kms::Model.find(templatable_type.to_i)
      model.entries
    end

  end
end

app/models/kms/settings.rb
module Kms
  class Settings < ActiveRecord::Base

    serialize :values

    def self.instance
      first_or_create
    end

    def self.get(key)
      instance.values[key]
    end

    def self.set(key, value)
      settings = instance
      settings.values[key] = value
      settings.save!
    end
  end
end

app/models/kms/snippet.rb
module Kms
  class Snippet < ActiveRecord::Base
    include CompileTemplates

    validates :name, :slug, presence: true

    def register_id
      ['_', slug].join
    end
  end
end

app/models/kms/string_field.rb
module Kms
  class StringField < Field
  end
end

app/models/kms/template.rb
module Kms
  class Template < ActiveRecord::Base
    include CompileTemplates

    validates :name, presence: true

  end
end

app/models/kms/text_field.rb
module Kms
  class TextField < Field
  end
end

app/views/layouts/kms/devise.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>APIQ</title>

    <%= stylesheet_link_tag    'kms/application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Bootstrap core CSS -->

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

  <body>

    <div class="container">

      <%= yield %>

    </div> <!-- /container -->

</body></html>

app/views/layouts/kms/kms.html.erb
<!doctype html>
<html lang="en" ng-app="KMS">
<head>
	<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

	<title>{{ 'APIQ - ' + ($state.current.views['header'] || $state.current.views['header@']).template || 'APIQ' }}</title>
  <%= stylesheet_link_tag    'kms/application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript">
     var CKEDITOR_BASEPATH = '/assets/ng-ckeditor/libs/ckeditor/';
   </script>
  <%= csrf_meta_tags %>

  <!-- build:js js/dashboard.js -->
  <!-- endbuild -->
  <!-- SCRIPTS -->
	<base href="/">

</head>
<body>
  <div id="page-wrapper" ng-controller="SidebarController" ng-class="{'open': toggle}" ng-cloak>

    <!-- Sidebar -->

    <div id="sidebar-wrapper">
      <ul class="sidebar">
        <li class="sidebar-main">
          <a href="#" ng-click="toggleSidebar()">
						<svg
						xmlns:dc="http://purl.org/dc/elements/1.1/"
						xmlns:cc="http://creativecommons.org/ns#"
						xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
						xmlns:svg="http://www.w3.org/2000/svg"
						xmlns="http://www.w3.org/2000/svg"
						viewBox="0 0 1250 1250"
						height="70"
						width="70"
						xml:space="preserve"
						version="1.1"
						preserveAspectRation="none"
						id="svg2" class="logo"><metadata
						id="metadata8"><rdf:RDF><cc:Work
						rdf:about=""><dc:format>image/svg+xml</dc:format><dc:type
						rdf:resource="http://purl.org/dc/dcmitype/StillImage" /></cc:Work></rdf:RDF></metadata><defs
						id="defs6"><clipPath
						id="clipPath16"
						clipPathUnits="userSpaceOnUse"><path
						id="path18"
						d="m 0,1000 1000,0 L 1000,0 0,0 0,1000 Z" /></clipPath></defs><g
						transform="matrix(1.25,0,0,-1.25,0,1250)"
						id="g10"><g
						id="g12"><g
						clip-path="url(#clipPath16)"
						id="g14"><g
						transform="translate(448.853,608.1104)"
						id="g20"><path
						id="path22"
						style="fill:#ff5274;fill-opacity:1;fill-rule:nonzero;stroke:none"
						d="m 0,0 48.851,25.155 c 1.443,0.743 3.157,0.743 4.601,-0.001 L 102.295,0 c 3.633,-1.87 3.632,-7.063 0,-8.933 L 53.447,-34.088 c -1.443,-0.743 -3.157,-0.743 -4.6,0 L 0,-8.934 C -3.632,-7.063 -3.632,-1.871 0,0" /></g><g
						transform="translate(512.4707,338.8955)"
						id="g24"><path
						id="path26"
						style="fill:#ff5274;fill-opacity:1;fill-rule:nonzero;stroke:none"
						d="m 0,0 c -7.808,-4.021 -17.133,-4.021 -24.94,0 l -240.019,123.607 62.093,31.978 161.765,-83.31 c 8.965,-4.617 18.798,-6.925 28.633,-6.925 9.832,0 19.666,2.308 28.626,6.925 L 177.926,155.585 240.02,123.607 0,0 Z m -138.643,226.155 36.404,-18.748 61.138,-31.487 c 8.965,-4.617 18.798,-6.926 28.633,-6.926 9.832,0 19.666,2.309 28.626,6.926 l 61.144,31.487 36.405,18.746 62.091,-31.975 -36.405,-18.749 -139.394,-71.784 c -7.808,-4.033 -17.13,-4.021 -24.941,0 l -139.389,71.784 -36.405,18.749 62.093,31.977 z m 112.084,95.218 1.622,0.835 c 7.807,4.025 17.129,4.014 24.94,0 L 1.626,321.372 111.576,264.748 77.3,247.097 75.171,246 38.766,227.252 -0.001,207.289 c -7.808,-4.026 -17.13,-4.015 -24.941,0 l -38.763,19.963 -36.403,18.747 -2.132,1.098 -34.275,17.651 109.956,56.625 z m 297.835,-174.174 -56.722,29.213 c 4.34,4.79 6.883,11.046 6.883,17.766 0,9.975 -5.507,19.015 -14.382,23.592 l -56.722,29.211 c 4.342,4.792 6.886,11.049 6.886,17.767 0,9.976 -5.51,19.015 -14.386,23.592 l -126.67,65.236 c -17.929,9.235 -39.337,9.24 -57.26,0 l -126.674,-65.236 -0.007,0 c -8.869,-4.577 -14.38,-13.616 -14.38,-23.592 0,-6.718 2.545,-12.975 6.889,-17.767 l -56.722,-29.211 -0.006,0 c -8.87,-4.571 -14.382,-13.611 -14.382,-23.592 0,-6.72 2.543,-12.975 6.883,-17.765 l -56.726,-29.214 c -8.868,-4.577 -14.379,-13.616 -14.379,-23.592 0,-9.975 5.511,-19.015 14.387,-23.592 L -41.098,-31.369 c 8.965,-4.617 18.795,-6.926 28.629,-6.926 9.832,0 19.665,2.309 28.627,6.926 l 255.126,131.39 c 8.867,4.571 14.375,13.611 14.375,23.586 0,9.976 -5.508,19.015 -14.383,23.592" /></g></g></g></g></svg>
            APIQ
            <span class="menu-icon glyphicon glyphicon-transfer"></span>
          </a>
        </li>
        <% Kms::ResourceService.resources.each do |group, resources| %>
          <% if resources.keys.any? {|r| can?(:index, r)} %>
            <li class="sidebar-title"><span><%= t(group) %></span></li>
          <% end %>
          <% resources.each do |resource_class, tab_icon_class| %>
            <% if can? :index, resource_class %>
              <li class="sidebar-list" ui-sref-active-eq="active">
                <a ui-sref="<%= defined?(Kms::Model) && resource_class.is_a?(Kms::Model) ? "models.entries({modelId: #{resource_class.name}})" : resource_class.name.demodulize.tableize %>" title="<%= resource_class.model_name.human(count: 1.1) %>">
                  <%= truncate(resource_class.model_name.human(count: 1.1), length: 22) %>
                  <span class="menu-icon fa <%= tab_icon_class %>"></span>
                </a>
              </li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
      <div class="sidebar-footer">
        <div class="col-xs-6">
          <a href="mailto:hello@apiq.io">
            <%= t(:need_help) %>
          </a>
        </div>
        <div class="col-xs-6">
          <a ui-sref="help">
            <%= t(:documentation) %>
          </a>
        </div>
      </div>
    </div>

    <!-- End Sidebar -->

    <div id="content-wrapper">
      <div class="page-content">

        <!-- Header Bar -->

        <div class="row header">
          <div class="col-xs-12">
            <div class="user pull-right">
              <div class="item dropdown">
                <a href="#" class="dropdown-toggle">
									<%= image_tag "avatar.jpg" %>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li class="dropdown-header">
                    <%= current_kms_user.try(:email) %>
                  </li>
                  <li class="divider"></li>
                  <li class="link">
                    <a ui-sref="settings">
                      <%= t(:settings) %>
                    </a>
                  </li>
                  <li class="link">
                    <%= link_to t(:sign_out), destroy_kms_user_session_path, target: "_self" %>
                  </li>
                </ul>
              </div>
              <!--
              <div class="item dropdown">
               <a href="#" class="dropdown-toggle">
                  <i class="fa fa-bell-o"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li class="dropdown-header">
                    Notifications
                  </li>
                  <li class="divider"></li>
                  <li>
                    <a href="#">Server Down!</a>
                  </li>
                </ul>
              </div>
              -->
            </div>
            <div class="meta">
              <div class="page" ui-view="header">
              </div>
              <!--
              <div class="breadcrumb-links">
                Home / Dashboard
              </div>-->
            </div>
          </div>
        </div>

        <!-- End Header Bar -->

        <!-- Main Content -->
        <section ui-view></section>
      </div><!-- End Page Content -->
    </div><!-- End Content Wrapper -->
  </div><!-- End Page Wrapper -->

  <%= javascript_include_tag 'kms/application', 'data-turbolinks-track' => true %>

  <script type="application/javascript">
    CKEDITOR.on('dialogDefinition', function (e) {
      var dialogName = e.data.name;
      var dialog = e.data.definition.dialog;
      dialog.on('show', function () {
        console.log(dialog.definition.contents[2].elements);
        console.log(dialog.definition.dialog.parts.contents);
      });
      dialog.on('hide', function () {
      });
    });
  </script>
</body>
</html>